test the build

diff --git a/.github/workflows/pythonapp.yml b/.github/workflows/pythonapp.yml
--- a/.github/workflows/pythonapp.yml
+++ b/.github/workflows/pythonapp.yml
@@ -85,6 +85,23 @@ jobs:
         file: ./coverage.xml
         flags: unittests
         token: ${{ secrets.CODECOV_TOKEN }}
+    - name: Test build
+      run: |
+        python -m pip install build
+        python -m build
+    - name: Test pip install whl
+      run: |
+        python -m pip install venv
+        python -m venv test-install-venv
+        source test-install-venv/bin/activate
+        whl_file=$(ls -1 dist/vasim-*.whl)
+        test $(echo "$whl_file" | wc -l) -eq 1 || { echo "Error: Incorrect number of wheel files found: '$whl_file'"; exit 1; }
+        python -m pip install "$whl_file[dev]"
+        # Run a single basic test that uses the package modules.
+        grep -q '^from vasim.recommender' tests/test_metrics_data_window.py
+        grep -q '^from vasim.simulator' tests/test_metrics_data_window.py
+        pytest --no-cov -n0 tests/test_metrics_data_window.py
+        deactivate
 
   # TODO: set this up later too. It needs to be in a separate block below due to the permissions
   # page-build:
