Prepare a pipeline for publishing releases to pypi (#84)
# Pull Request

## Title

Prepares a Github Actions workflow for publishing releases to pypi.org

---

## Description

- Bumps the patch version to allow a release to happen.
- [x] Document release process.
- Closes #58 
---

## Type of Change

- ✨ New feature  

---

## Testing

- [x] Add tests of the build and install process in the regular CI
pipeline.

---

diff --git a/.github/workflows/pythonapp.yml b/.github/workflows/pythonapp.yml
--- a/.github/workflows/pythonapp.yml
+++ b/.github/workflows/pythonapp.yml
@@ -40,6 +40,9 @@ jobs:
       uses: actions/setup-python@v5
       with:
         python-version: ${{ matrix.python-version }}
+    - name: Update pip
+      run: |
+        python -m pip install --upgrade pip
     - name: Lint with flake8
       run: |
         python -m pip install --upgrade pip
@@ -65,16 +68,17 @@ jobs:
         python -m pip install pre-commit
         pre-commit run --all-files
         git diff --exit-code
-    - name: Install basic dependencies # TODO: separate out "test" dependencies in setup.py
+
+    - name: Install basic and test dependencies
       run: |
         python -m pip install -e .[dev]
-        python -m pip install jupyter
     - name: Tests with coverage reporting
       run : |
         # Run tests in parallel with coverage (configured via pyproject.toml)
         pytest
     - name: Test notebooks
       run: |
+        python -m pip install jupyter
         find . -name '*.ipynb' -print0 | xargs -0 -n1 -P0 python -m jupyter execute
         if [ $? != 0 ]; then
           echo "ERROR: Notebooks execution failed." >&2
@@ -88,6 +92,23 @@ jobs:
         file: ./coverage.xml
         flags: unittests
         token: ${{ secrets.CODECOV_TOKEN }}
+
+    - name: Test build whl
+      run: |
+        python -m pip install build
+        python -m build
+    - name: Test pip install whl
+      run: |
+        python -m venv test-install-venv
+        source test-install-venv/bin/activate
+        whl_file=$(ls -1 dist/vasim-*.whl)
+        test $(echo "$whl_file" | wc -l) -eq 1 || { echo "Error: Incorrect number of wheel files found: '$whl_file'"; exit 1; }
+        python -m pip install "$whl_file[dev]"
+        # Run a single basic test that uses the package modules.
+        grep -q '^from vasim.recommender' tests/test_metrics_data_window.py
+        grep -q '^from vasim.simulator' tests/test_metrics_data_window.py
+        pytest --no-cov -n0 tests/test_metrics_data_window.py
+        deactivate
 
   # TODO: set this up later too. It needs to be in a separate block below due to the permissions
   # page-build:
